language: generic # default to ruby
matrix:
    include:
        - os: osx
          osx_image: xcode8
          install:
              - ./.travis-nanomsg.sh
        - os: linux
          sudo: required
          dist: trusty
          install:
              - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
              - ./.travis-nanomsg.sh
          cache:
              directories:
                  - $HOME/.swiftenv
                  - $HOME/.nanomsg
script:
   - swift test
